version: '3'
services:
  cards: # container name
    build: cards-app
    volumes:
      - ./cardchain.json:/home/app/static/cardchain.json:ro
      - ./output-cards:/home/app/static/output-cards:ro
    networks:
      - nginx-cards

  nginx:
    image: nginx:alpine
    ports: 
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx-cards
    depends_on:
      - cards

networks:
  nginx-cards:
